# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from btx.api.v1.customer.betting import betting_api_pb2 as btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in btx/api/v1/customer/betting/betting_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BettingApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMarketData = channel.unary_stream(
                '/btx.api.v1.customer.betting.BettingApi/StreamMarketData',
                request_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.StreamMarketDataRequest.SerializeToString,
                response_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.MarketDataStreamingMessage.FromString,
                _registered_method=True)
        self.PlaceOrders = channel.unary_unary(
                '/btx.api.v1.customer.betting.BettingApi/PlaceOrders',
                request_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.PlaceOrdersRequest.SerializeToString,
                response_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.PlaceOrdersResponse.FromString,
                _registered_method=True)
        self.CancelOrders = channel.unary_unary(
                '/btx.api.v1.customer.betting.BettingApi/CancelOrders',
                request_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.CancelOrdersRequest.SerializeToString,
                response_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.CancelOrdersResponse.FromString,
                _registered_method=True)
        self.UpdateAutoCancel = channel.unary_unary(
                '/btx.api.v1.customer.betting.BettingApi/UpdateAutoCancel',
                request_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.UpdateAutoCancelRequest.SerializeToString,
                response_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.UpdateAutoCancelResponse.FromString,
                _registered_method=True)


class BettingApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAutoCancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BettingApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMarketData,
                    request_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.StreamMarketDataRequest.FromString,
                    response_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.MarketDataStreamingMessage.SerializeToString,
            ),
            'PlaceOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrders,
                    request_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.PlaceOrdersRequest.FromString,
                    response_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.PlaceOrdersResponse.SerializeToString,
            ),
            'CancelOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrders,
                    request_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.CancelOrdersRequest.FromString,
                    response_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.CancelOrdersResponse.SerializeToString,
            ),
            'UpdateAutoCancel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAutoCancel,
                    request_deserializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.UpdateAutoCancelRequest.FromString,
                    response_serializer=btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.UpdateAutoCancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'btx.api.v1.customer.betting.BettingApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('btx.api.v1.customer.betting.BettingApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BettingApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/btx.api.v1.customer.betting.BettingApi/StreamMarketData',
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.StreamMarketDataRequest.SerializeToString,
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.MarketDataStreamingMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/btx.api.v1.customer.betting.BettingApi/PlaceOrders',
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.PlaceOrdersRequest.SerializeToString,
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.PlaceOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/btx.api.v1.customer.betting.BettingApi/CancelOrders',
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.CancelOrdersRequest.SerializeToString,
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.CancelOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAutoCancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/btx.api.v1.customer.betting.BettingApi/UpdateAutoCancel',
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.UpdateAutoCancelRequest.SerializeToString,
            btx_dot_api_dot_v1_dot_customer_dot_betting_dot_betting__api__pb2.UpdateAutoCancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
